name: publish

on: [push]

jobs:
  publish-mongodb-ci-connector:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the mongodb-bi-connector Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u phlaxyz --password-stdin
        docker build . --tag ghcr.io/phlaxyz/mongodb-bi-connector-docker:latest
        docker run ghcr.io/phlaxyz/mongodb-bi-connector-docker:latest
        docker push ghcr.io/phlaxyz/mongodb-bi-connector-docker:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

